
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: react-app-elproyectoia
    ports:
      - "8083:80"
    restart: unless-stopped
    networks:
      - app-network-proyectoia
    environment:
      - NODE_ENV=production

networks:
  app-network-proyectoia:
    driver: bridge 